name: Terraform

on:
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform Workflow
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Terraform
        run: |
          wget https://releases.hashicorp.com/terraform/1.9.7/terraform_1.9.7_darwin_amd64.zip
          unzip terraform_1.9.7_darwin_amd64.zip
          sudo mv terraform /usr/local/bin/

      - name: Initialize Terraform
        run: terraform init

      - name: Terraform Format Check
        run: |
          terraform fmt -check
          terraform fmt

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan
