name: Terraform

on:
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform Workflow
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.7

      - name: Initialize Terraform
        run: terraform init

      - name: Terraform Format Check
        run: |
          terraform fmt -check
          terraform fmt

      - name: Terraform Validate
        run: terraform validate