# name: Terraform

# on:
#   pull_request:
#     branches:
#       - "main"
#   workflow_dispatch:

# jobs:
#   terraform:
#     name: Terraform
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2

#       - name: Install Terraform
#         run: |
#           wget https://releases.hashicorp.com/terraform/1.7.0/terraform_1.7.0_linux_amd64.zip
#           unzip terraform_1.7.0_linux_amd64.zip
#           sudo mv terraform /usr/local/bin/

#       - name: Terraform Format
#         id: fmt
#         run: |
#             # terraform fmt
#             terraform fmt -check

#       - name: Terraform Init
#         id: init
#         run: terraform init

#       - name: Terraform Validate
#         id: validate
#         run: terraform validate

name: Terraform

on:
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform Workflow
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Terraform
        run: |
          wget https://releases.hashicorp.com/terraform/1.9.7/terraform_1.9.7_darwin_amd64.zip
          unzip terraform_1.9.7_darwin_amd64.zip
          sudo mv terraform /usr/local/bin/

      - name: Terraform Format Check
        run: |
          # terraform fmt
          terraform fmt -check

      - name: Initialize Terraform
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

   
